services:

  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
      DEBUG: "True"

  celery:
    volumes:
      - ./backend:/app

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    command: python run_bot.py
    volumes:
      - ./backend:/app/backend
      - ./bot:/app/bot
      - ./run_bot.py:/app/run_bot.py
    env_file: .env
    environment:
      API_BASE_URL: http://web:8000

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
