# Generated by Django 5.0 on 2026-04-02 23:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date joined",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        unique=True, verbose_name="Telegram ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="ru",
                        max_length=8,
                        verbose_name="Язык интерфейса",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("secure", "Надёжный"),
                            ("anxious", "Тревожный"),
                            ("avoidant", "Избегающий"),
                            ("disorganized", "Дезорганизованный"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Тип привязанности",
                    ),
                ),
                (
                    "attachment_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bot_test", "Тест в боте"),
                            ("user_defined", "Указан вручную"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Источник типа привязанности",
                    ),
                ),
                (
                    "correction_coefficient",
                    models.FloatField(
                        default=1.0,
                        verbose_name="Поправочный коэффициент скоринга",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.CreateModel(
            name="UserTokenLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_limit",
                    models.IntegerField(
                        default=10000, verbose_name="Дневной лимит токенов"
                    ),
                ),
                (
                    "monthly_limit",
                    models.IntegerField(
                        default=100000, verbose_name="Месячный лимит токенов"
                    ),
                ),
                (
                    "used_today",
                    models.IntegerField(
                        default=0, verbose_name="Использовано сегодня"
                    ),
                ),
                (
                    "used_this_month",
                    models.IntegerField(
                        default=0, verbose_name="Использовано в этом месяце"
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Бесплатный"),
                            ("pro", "Pro"),
                            ("trial", "Пробный"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "reset_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Время следующего сброса",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_limit",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лимит токенов",
                "verbose_name_plural": "Лимиты токенов",
            },
        ),
    ]
