# Generated by Django 5.0 on 2026-04-02 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_test_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="correction_coefficient",
            field=models.FloatField(
                default=1.0,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(1.5),
                ],
                verbose_name="Поправочный коэффициент скоринга",
            ),
        ),
    ]
