# Generated by Django 5.0 on 2026-04-03 00:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        ("criteria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_text",
                    models.TextField(
                        verbose_name="Текст события (оригинал пользователя)"
                    ),
                ),
                (
                    "ai_interpretation",
                    models.TextField(
                        blank=True, verbose_name="Интерпретация ИИ"
                    ),
                ),
                (
                    "is_hard_stop",
                    models.BooleanField(
                        default=False, verbose_name="Триггернуло Hard Stop"
                    ),
                ),
                (
                    "bias_warning",
                    models.TextField(
                        blank=True,
                        verbose_name="Предупреждение о когнитивном искажении",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время события"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="candidates.candidate",
                        verbose_name="Кандидат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIProviderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("claude", "Claude"),
                            ("gemini", "Gemini"),
                            ("openai", "OpenAI"),
                        ],
                        max_length=20,
                        verbose_name="Провайдер",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(verbose_name="Отправленный промпт"),
                ),
                (
                    "response",
                    models.TextField(verbose_name="Ответ провайдера"),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0, verbose_name="Использовано токенов"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время запроса"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_logs",
                        to="events.event",
                        verbose_name="Событие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог AI провайдера",
                "verbose_name_plural": "Логи AI провайдера",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventCriterionScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_score",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(-2),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="Балл ИИ (-2..+2)",
                    ),
                ),
                (
                    "user_score",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-2),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="Балл пользователя (-2..+2)",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False,
                        verbose_name="Пользователь подтвердил оценку",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="criteria.criterion",
                        verbose_name="Критерий",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="events.event",
                        verbose_name="Событие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка события",
                "verbose_name_plural": "Оценки событий",
                "ordering": ["event", "criterion"],
                "unique_together": {("event", "criterion")},
            },
        ),
    ]
