# Generated by Django 5.0 on 2026-04-02 23:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Criterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, verbose_name="Название"),
                ),
                (
                    "weight",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Вес критерия (0.0–1.0)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Что измеряется"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        verbose_name="Системный (предустановленный)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Критерий оценки",
                "verbose_name_plural": "Критерии оценки",
                "ordering": ["-is_default", "-weight"],
            },
        ),
        migrations.CreateModel(
            name="HardStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Название"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Описание и логика"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        verbose_name="Системный (предустановленный)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hard_stops",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hard Stop",
                "verbose_name_plural": "Hard Stops",
                "ordering": ["-is_default", "name"],
            },
        ),
    ]
