# Generated by Django 5.0 on 2026-04-02 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("criteria", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Имя / псевдоним"
                    ),
                ),
                (
                    "age",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Возраст"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="candidates/photos/%Y/%m/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "met_at",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Место / обстоятельства знакомства",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активный кандидат"
                    ),
                ),
                (
                    "hard_stop_triggered",
                    models.BooleanField(
                        default=False, verbose_name="Сработал Hard Stop"
                    ),
                ),
                (
                    "ai_attachment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("secure", "Надёжный"),
                            ("anxious", "Тревожный"),
                            ("avoidant", "Избегающий"),
                            ("disorganized", "Дезорганизованный"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Тип привязанности (определён ИИ)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кандидат",
                "verbose_name_plural": "Кандидаты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CandidateHardStopLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата срабатывания"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, verbose_name="Описание события-триггера"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hard_stop_logs",
                        to="candidates.candidate",
                        verbose_name="Кандидат",
                    ),
                ),
                (
                    "hard_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="criteria.hardstop",
                        verbose_name="Hard Stop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог Hard Stop",
                "verbose_name_plural": "Логи Hard Stop",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="CandidateStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("meeting", "Знакомство"),
                            ("dating", "Встречаемся"),
                            ("serious", "Серьёзно"),
                            ("pause", "Пауза"),
                            ("ended", "Завершено"),
                        ],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата установки статуса",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, verbose_name="Причина смены статуса"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="candidates.candidate",
                        verbose_name="Кандидат",
                    ),
                ),
            ],
            options={
                "verbose_name": "История статусов",
                "verbose_name_plural": "История статусов",
                "ordering": ["-started_at"],
            },
        ),
    ]
