# Generated by Django 5.2.12 on 2026-04-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="telegram_photo_id",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Telegram file_id фото",
            ),
        ),
    ]
