# Generated by Django 5.2.12 on 2026-05-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_candidate_telegram_photo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatestatushistory",
            name="ended_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата завершения статуса"
            ),
        ),
    ]
