# Generated by Django 5.0 on 2026-04-02 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        verbose_name="Название теста",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Описание методологии"
                    ),
                ),
                (
                    "questions_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество вопросов"
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False, verbose_name="Академически валидирован"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Доступен пользователям"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест привязанности",
                "verbose_name_plural": "Тесты привязанности",
                "ordering": ["-is_validated", "name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("anxiety", "Тревожность"),
                            ("avoidance", "Избегание"),
                        ],
                        max_length=20,
                        verbose_name="Измерение",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(default=1.0, verbose_name="Вес вопроса"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessments.attachmenttest",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["test", "order"],
            },
        ),
        migrations.CreateModel(
            name="UserTestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("secure", "Надёжный"),
                            ("anxious", "Тревожный"),
                            ("avoidant", "Избегающий"),
                            ("disorganized", "Дезорганизованный"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Результат теста",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="assessments.attachmenttest",
                        verbose_name="Тест",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия теста",
                "verbose_name_plural": "Сессии тестов",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.SmallIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                        ],
                        verbose_name="Ответ (1–5)",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assessments.question",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="assessments.usertestsession",
                        verbose_name="Сессия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на вопрос",
                "verbose_name_plural": "Ответы на вопросы",
                "unique_together": {("session", "question")},
            },
        ),
    ]
