# Generated by Django 5.0 on 2026-04-02 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="weight",
            field=models.FloatField(
                default=1.0,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="Вес вопроса",
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="answer",
            field=models.SmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Ответ (1–5)",
            ),
        ),
    ]
