# Generated by Django 5.2.12 on 2026-05-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_alter_question_weight_alter_useranswer_answer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachmenttest",
            options={
                "ordering": ("-is_validated", "name"),
                "verbose_name": "Тест привязанности",
                "verbose_name_plural": "Тесты привязанности",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ("test", "order"),
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.AlterModelOptions(
            name="usertestsession",
            options={
                "ordering": ("-completed_at",),
                "verbose_name": "Сессия теста",
                "verbose_name_plural": "Сессии тестов",
            },
        ),
    ]
